# Generated by Django 2.2.24 on 2022-03-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0004_theme_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='logo_path',
            field=models.CharField(blank=True, help_text='Link image logo.', max_length=300, verbose_name='Link logo'),
        ),
    ]
