# Generated by Django 2.2.24 on 2022-03-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0006_auto_20220306_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='font_other',
            field=models.CharField(blank=True, help_text='Name font from Google Font.', max_length=300, verbose_name='Font other'),
        ),
    ]
