# Generated by Django 2.2.24 on 2022-03-06 13:33

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0007_theme_font_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='background_website',
            field=colorful.fields.RGBColorField(blank=True, help_text='Color background website.', verbose_name='Color background website'),
        ),
    ]
