# Generated by Django 2.2.24 on 2022-03-06 13:48

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0009_theme_background_menu_dropdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='btn_color_default',
            field=colorful.fields.RGBColorField(blank=True, help_text='Color default button.', verbose_name='Color default button'),
        ),
        migrations.AddField(
            model_name='theme',
            name='btn_color_primary',
            field=colorful.fields.RGBColorField(blank=True, help_text='Color primary button.', verbose_name='Color primary button'),
        ),
        migrations.AddField(
            model_name='theme',
            name='btn_color_success',
            field=colorful.fields.RGBColorField(blank=True, help_text='Color success button.', verbose_name='Color success button'),
        ),
    ]
