# Generated by Django 2.2.24 on 2022-03-06 13:51

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0010_auto_20220306_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='btn_color_danger',
            field=colorful.fields.RGBColorField(blank=True, help_text='Color danger button.', verbose_name='Color danger button'),
        ),
    ]
