# Generated by Django 2.2.24 on 2022-03-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0011_theme_btn_color_danger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='logo_path',
            field=models.TextField(blank=True, verbose_name='Path logo'),
        ),
    ]
