# Generated by Django 2.2.24 on 2022-03-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0012_auto_20220307_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='font_size_header',
            field=models.IntegerField(default=20, help_text='Font size header brand.', verbose_name='Font size brand'),
        ),
    ]
