# Generated by Django 2.2.24 on 2022-03-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0016_theme_menu_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='javascript_data',
            field=models.TextField(blank=True, help_text='Javascript Data.', verbose_name='Javascript'),
        ),
    ]
