# Generated by Django 2.2.24 on 2022-03-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0017_theme_javascript_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='status_theme',
            field=models.CharField(choices=[(True, 'On'), (False, 'Off')], default=True, max_length=100, verbose_name='Status Theme'),
        ),
    ]
