# Generated by Django 2.2.24 on 2022-03-18 16:38

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0018_theme_status_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='btn_color_danger',
            field=colorful.fields.RGBColorField(blank=True, default='#fffff', help_text='Color danger button.', verbose_name='Color danger button'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='btn_color_primary',
            field=colorful.fields.RGBColorField(blank=True, default='#252525', help_text='Color primary button.', verbose_name='Color primary button'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='javascript_data',
            field=models.TextField(blank=True, verbose_name='Javascript'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='status_theme',
            field=models.CharField(choices=[('On', 'On'), ('Off', 'Off')], default='Off', max_length=100, verbose_name='Status Theme'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='stylesheet',
            field=models.TextField(blank=True, verbose_name='Stylesheet'),
        ),
    ]
