# Generated by Django 2.2.24 on 2022-03-18 16:41

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0019_auto_20220318_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='btn_color_danger',
            field=colorful.fields.RGBColorField(blank=True, default='#dc3545', help_text='Color danger button.', verbose_name='Color danger button'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='btn_color_default',
            field=colorful.fields.RGBColorField(blank=True, default='#17a2b8', help_text='Color default button.', verbose_name='Color default button'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='btn_color_primary',
            field=colorful.fields.RGBColorField(blank=True, default='#007bff', help_text='Color primary button.', verbose_name='Color primary button'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='btn_color_success',
            field=colorful.fields.RGBColorField(blank=True, default='#28a745', help_text='Color success button.', verbose_name='Color success button'),
        ),
    ]
